const OFFICIAL_KNOWLEDGE_ENTRIES = require("./official-knowledge-entries.json");
const TECHNICAL_LEARNING_KNOWLEDGE_ENTRIES = require("./technical-learning-knowledge-entries.json");

const OFFICIAL_SOURCE_REGISTRY = Object.freeze([
  Object.freeze({
    id: "moe-postgraduate-admissions",
    goal_type: "postgraduate_entrance_exam",
    title: "全国硕士研究生招生工作相关规定",
    publisher: "教育部",
    official_url: "https://www.moe.gov.cn/",
    use_for: "年度招生政策、管理规定和官方通知",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "chsi-postgraduate-directory",
    goal_type: "postgraduate_entrance_exam",
    title: "中国研究生招生信息网",
    publisher: "教育部学生服务与素质发展中心",
    official_url: "https://yz.chsi.com.cn/",
    use_for: "招生单位、专业目录和报名信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "target-university-graduate-school",
    goal_type: "postgraduate_entrance_exam",
    title: "目标院校研究生院与招生单位公告",
    publisher: "对应招生单位",
    official_url: "https://yz.chsi.com.cn/kyzx/yxzc/",
    use_for: "招生章程、科目调整、复试和录取信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "university-official-guidance",
    goal_type: "postgraduate_entrance_exam",
    title: "高校官方公开学习资料",
    publisher: "对应高校",
    official_url: "https://scie.zjgsu.edu.cn/",
    use_for: "术语解释和经验框架，仅作参考，不替代招生政策",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-civil-service-bureau",
    goal_type: "civil_service_exam",
    title: "国家公务员局",
    publisher: "国家公务员局",
    official_url: "https://www.scs.gov.cn/",
    use_for: "中央机关及其直属机构考试录用公告和职位信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "regional-civil-service-notices",
    goal_type: "civil_service_exam",
    title: "省级公务员主管部门公告",
    publisher: "对应省级公务员主管部门",
    official_url: "https://www.gov.cn/",
    use_for: "省考地区公告、职位表和资格条件",
    freshness: "regional_annual",
    region_scope: "按报考地区",
  }),
  Object.freeze({
    id: "civil-service-experience-reference",
    goal_type: "civil_service_exam",
    title: "公务员考试公开经验参考资料",
    publisher: "公开教育媒体与培训机构",
    official_url: "https://www.scs.gov.cn/",
    use_for: "备考方法、面试形式和选岗经验参考，不替代当年官方公告",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-college-employment-service",
    goal_type: "employment",
    title: "国家大学生就业服务平台",
    publisher: "教育部",
    official_url: "https://www.ncss.cn/",
    use_for: "校园招聘、就业服务和毕业生就业信息",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "mohrss-skill-evaluation",
    goal_type: "professional_certificate",
    title: "技能人才评价工作网",
    publisher: "人力资源和社会保障部相关评价服务",
    official_url: "https://www.osta.org.cn/",
    use_for: "职业技能等级评价、证书查询和评价机构信息",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-smart-education-platform",
    goal_type: "personal_growth",
    title: "国家智慧教育公共服务平台",
    publisher: "教育部",
    official_url: "https://www.smartedu.cn/",
    use_for: "公开学习资源和课程目录",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-official-learning",
    goal_type: "personal_growth",
    title: "技术官方文档与公开课程",
    publisher: "MDN、语言与框架官方文档及公开课程平台",
    official_url: "https://developer.mozilla.org/zh-CN/docs/Learn_web_development",
    use_for: "计算机基础、编程语言、框架和开发工具的原理与学习资源；具体版本以官方文档为准",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-industry-reference",
    goal_type: "personal_growth",
    title: "技术岗位与行业参考资料",
    publisher: "牛客网等公开招聘与技术社区资料",
    official_url: "https://www.nowcoder.com/",
    use_for: "岗位方向、技能栈和行业经验参考，不替代招聘方当前要求或官方政策",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-certification-reference",
    goal_type: "personal_growth",
    title: "计算机技术资格与认证官方入口",
    publisher: "中国计算机技术职业资格网及相关认证机构",
    official_url: "https://www.ruankao.org.cn/",
    use_for: "软考与技术认证的考试安排、资格、科目和证书规则核验",
    freshness: "annual",
    region_scope: "全国",
  }),
]);

// These are reviewed retrieval anchors, not claims about a current year's dates or eligibility.
// Dynamic facts remain facts_to_confirm and must be checked at the official source.
const BASE_OFFICIAL_KNOWLEDGE_CHUNKS = Object.freeze([
  Object.freeze({
    id: "pg-policy-verification",
    source_id: "moe-postgraduate-admissions",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研政策与管理信息的核验范围",
    content: "涉及考研报名条件、招生管理、考试组织、年度政策或通知时，计划只能把教育部及当年官方公告作为核验依据。模型不得把往年时间、资格条件或经验判断写成今年已经确定的事实。",
    keywords: ["考研", "研究生", "报名", "资格", "政策", "公告", "年度", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "pg-directory-verification",
    source_id: "chsi-postgraduate-directory",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研院校、专业目录与报名信息",
    content: "涉及目标院校、招生单位、专业目录、报名信息或报考地区时，应把中国研究生招生信息网的当年页面作为检索和核验入口。目标院校的具体要求还需要继续核对该校研究生院或招生单位公告。",
    keywords: ["考研", "院校", "专业目录", "招生单位", "报名", "地区", "专业课", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "pg-plan-evidence",
    source_id: "chsi-postgraduate-directory",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研计划的可追溯学习产出",
    content: "考研学习计划应将目标拆成可检查的阶段产出，例如完成范围清单、留下基础诊断、完成错题回顾和形成专业课复述。计划中的动态考试事实必须单独列为待核验事项，不应由模型替用户确认。",
    keywords: ["考研", "计划", "学习产出", "基础诊断", "错题", "专业课", "待核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-national-verification",
    source_id: "national-civil-service-bureau",
    goal_types: ["civil_service_exam"],
    region_scope: "全国",
    title: "国考公告与职位信息的核验范围",
    content: "涉及中央机关及其直属机构的考试公告、职位条件、报名安排或职位信息时，应以国家公务员局发布的当年公告和职位信息为依据。模型不得使用未核验的往年时间、岗位数量或资格条件。",
    keywords: ["考公", "国考", "公务员", "公告", "职位", "报名", "资格", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-regional-verification",
    source_id: "regional-civil-service-notices",
    goal_types: ["civil_service_exam"],
    region_scope: "按报考地区",
    title: "省考地区与资格条件的核验范围",
    content: "涉及省考、地区限制、职位表、资格条件或地方报名安排时，必须按用户报考地区检索对应省级公务员主管部门公告。全国性经验不能替代地方公告，地区不匹配时要标记为待核验。",
    keywords: ["考公", "省考", "地区", "职位表", "资格条件", "报名", "公告", "地方"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-plan-evidence",
    source_id: "national-civil-service-bureau",
    goal_types: ["civil_service_exam"],
    region_scope: "全国",
    title: "考公计划的可追溯学习产出",
    content: "考公学习计划应把行测、申论或用户明确的重点拆成可检查的练习、复盘和表达产出。具体考试科目、题型比例和当年要求必须回到对应公告或官方材料核验，不由模型凭记忆补全。",
    keywords: ["考公", "行测", "申论", "练习", "复盘", "表达", "计划", "待核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "shared-source-grounding",
    source_id: "national-smart-education-platform",
    goal_types: ["personal_growth", "employment", "professional_certificate"],
    region_scope: "全国",
    title: "学习资源与目标的来源边界",
    content: "平台可以根据用户目标、基础和可用时间组织学习计划，但课程、证书规则、就业行情或机构要求等外部事实必须标明来源和更新时间。没有可靠来源时，输出应该是学习行动建议，而不是确定性事实。",
    keywords: ["学习", "课程", "证书", "就业", "资源", "来源", "更新时间", "核验"],
    review_status: "reviewed",
  }),
]);

function importedKnowledgeChunk(entry) {
  const metadata = {
    level1: entry.level1,
    level2: entry.level2,
    audience: entry.audience,
    stage: entry.stage,
    region: entry.region,
    prerequisites: entry.prerequisites,
    related: entry.related,
    source_name: entry.source_name,
    source_type: entry.source_type,
    published_at: entry.published_at,
    validity: entry.validity,
    confidence: entry.confidence,
    update_required: entry.update_required,
    review_schedule: entry.review_schedule,
    claim_status: entry.claim_status,
    review_note: entry.review_note,
  };
  return Object.freeze({
    id: entry.id,
    source_id: entry.primary_source_id,
    goal_types: [entry.goal_type ?? "postgraduate_entrance_exam"],
    region_scope: entry.region,
    title: entry.title,
    content: [
      `知识结论：${entry.conclusion}`,
      `详细说明：${entry.detail}`,
      `前置条件：${entry.prerequisites}`,
      `可执行步骤：${entry.actions.join("；")}`,
      `常见误区：${entry.pitfalls}`,
      `审核边界：${entry.review_note}`,
    ].join("\n"),
    keywords: [...entry.tags, entry.level1, entry.level2, entry.related].filter(Boolean),
    source_links: [...entry.source_links],
    metadata,
    review_status: entry.review_status,
  });
}

const IMPORTED_KNOWLEDGE_CHUNKS = [
  ...OFFICIAL_KNOWLEDGE_ENTRIES,
  ...TECHNICAL_LEARNING_KNOWLEDGE_ENTRIES,
].map(importedKnowledgeChunk);
const OFFICIAL_KNOWLEDGE_CHUNKS = Object.freeze([
  ...BASE_OFFICIAL_KNOWLEDGE_CHUNKS,
  ...IMPORTED_KNOWLEDGE_CHUNKS,
]);

module.exports = {
  OFFICIAL_KNOWLEDGE_CHUNKS,
  OFFICIAL_SOURCE_REGISTRY,
};
