const OFFICIAL_KNOWLEDGE_ENTRIES = require("./official-knowledge-entries.json");
const TECHNICAL_LEARNING_KNOWLEDGE_ENTRIES = require("./technical-learning-knowledge-entries.json");
const POSTGRADUATE_PACK_KNOWLEDGE_ENTRIES = require("./2026-09-20-postgraduate-knowledge-entries.json");
const OFFICIAL_TECHNICAL_KNOWLEDGE_ENTRIES = require("./2026-09-20-official-technical-knowledge-entries.json");
const OFFICIAL_KNOWLEDGE_EXPANSION_V2_ENTRIES = require("./2026-09-20-official-knowledge-expansion-v2.json");
const GITHUB_LEARNING_RESEARCH_ENTRIES = require("./2026-09-20-github-learning-research-entries.json");

const OFFICIAL_SOURCE_REGISTRY = Object.freeze([
  Object.freeze({
    id: "moe-postgraduate-admissions",
    goal_type: "postgraduate_entrance_exam",
    title: "全国硕士研究生招生工作相关规定",
    publisher: "教育部",
    official_url: "https://www.moe.gov.cn/",
    use_for: "年度招生政策、管理规定和官方通知",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "chsi-postgraduate-directory",
    goal_type: "postgraduate_entrance_exam",
    title: "中国研究生招生信息网",
    publisher: "教育部学生服务与素质发展中心",
    official_url: "https://yz.chsi.com.cn/",
    use_for: "招生单位、专业目录和报名信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "target-university-graduate-school",
    goal_type: "postgraduate_entrance_exam",
    title: "目标院校研究生院与招生单位公告",
    publisher: "对应招生单位",
    official_url: "https://yz.chsi.com.cn/kyzx/yxzc/",
    use_for: "招生章程、科目调整、复试和录取信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "university-official-guidance",
    goal_type: "postgraduate_entrance_exam",
    title: "高校官方公开学习资料",
    publisher: "对应高校",
    official_url: "https://scie.zjgsu.edu.cn/",
    use_for: "术语解释和经验框架，仅作参考，不替代招生政策",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-civil-service-bureau",
    goal_type: "civil_service_exam",
    title: "国家公务员局",
    publisher: "国家公务员局",
    official_url: "https://www.scs.gov.cn/",
    use_for: "中央机关及其直属机构考试录用公告和职位信息",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "regional-civil-service-notices",
    goal_type: "civil_service_exam",
    title: "省级公务员主管部门公告",
    publisher: "对应省级公务员主管部门",
    official_url: "https://www.gov.cn/",
    use_for: "省考地区公告、职位表和资格条件",
    freshness: "regional_annual",
    region_scope: "按报考地区",
  }),
  Object.freeze({
    id: "civil-service-experience-reference",
    goal_type: "civil_service_exam",
    title: "公务员考试公开经验参考资料",
    publisher: "公开教育媒体与培训机构",
    official_url: "https://www.scs.gov.cn/",
    use_for: "备考方法、面试形式和选岗经验参考，不替代当年官方公告",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-college-employment-service",
    goal_type: "employment",
    title: "国家大学生就业服务平台",
    publisher: "教育部",
    official_url: "https://www.ncss.cn/",
    use_for: "校园招聘、就业服务和毕业生就业信息",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "mohrss-skill-evaluation",
    goal_type: "professional_certificate",
    title: "技能人才评价工作网",
    publisher: "人力资源和社会保障部相关评价服务",
    official_url: "https://www.osta.org.cn/",
    use_for: "职业技能等级评价、证书查询和评价机构信息",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "national-smart-education-platform",
    goal_type: "personal_growth",
    title: "国家智慧教育公共服务平台",
    publisher: "教育部",
    official_url: "https://www.smartedu.cn/",
    use_for: "公开学习资源和课程目录",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-official-learning",
    goal_type: "personal_growth",
    title: "技术官方文档与公开课程",
    publisher: "MDN、语言与框架官方文档及公开课程平台",
    official_url: "https://developer.mozilla.org/zh-CN/docs/Learn_web_development",
    use_for: "计算机基础、编程语言、框架和开发工具的原理与学习资源；具体版本以官方文档为准",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-industry-reference",
    goal_type: "personal_growth",
    title: "技术岗位与行业参考资料",
    publisher: "牛客网等公开招聘与技术社区资料",
    official_url: "https://www.nowcoder.com/",
    use_for: "岗位方向、技能栈和行业经验参考，不替代招聘方当前要求或官方政策",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "technical-certification-reference",
    goal_type: "personal_growth",
    title: "计算机技术资格与认证官方入口",
    publisher: "中国计算机技术职业资格网及相关认证机构",
    official_url: "https://www.ruankao.org.cn/",
    use_for: "软考与技术认证的考试安排、资格、科目和证书规则核验",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "neea-postgraduate-exam",
    goal_type: "postgraduate_entrance_exam",
    title: "教育部教育考试院研究生考试相关信息",
    publisher: "教育部教育考试院",
    official_url: "https://www.neea.edu.cn/",
    use_for: "统考科目考试大纲编写方和命题相关政策；具体年度内容以正式文件为准",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "hep-postgraduate-exam-outline",
    goal_type: "postgraduate_entrance_exam",
    title: "高等教育出版社统考考试大纲",
    publisher: "高等教育出版社",
    official_url: "https://www.hep.com.cn/",
    use_for: "统考考试大纲出版与版本核对；不替代教育部和研招网公告",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "jiangxi-exam-authority",
    goal_type: "postgraduate_entrance_exam",
    title: "江西省教育考试院",
    publisher: "江西省教育考试院",
    official_url: "http://www.jxeea.cn/",
    use_for: "江西省网报公告、报考点规则和网上确认安排",
    freshness: "regional_annual",
    region_scope: "江西",
  }),
  Object.freeze({
    id: "chsi-public-info",
    goal_type: "postgraduate_entrance_exam",
    title: "全国硕士生招生信息公开平台",
    publisher: "教育部学生服务与素质发展中心",
    official_url: "https://yz.chsi.com.cn/",
    use_for: "拟录取公示和招生信息公开核验",
    freshness: "annual",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "china-education-online-postgraduate",
    goal_type: "postgraduate_entrance_exam",
    title: "中国教育在线考研频道",
    publisher: "中国教育在线",
    official_url: "https://kaoyan.eol.cn/",
    use_for: "政策解读和大纲对比线索；政策结论必须回链T1来源",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "wangdao-postgraduate-teaching",
    goal_type: "postgraduate_entrance_exam",
    title: "王道论坛与王道考研教研",
    publisher: "王道考研教研",
    official_url: "",
    use_for: "408学习方法和经验框架；仅作T3教研参考，不作为政策依据",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "koolearn-postgraduate-teaching",
    goal_type: "postgraduate_entrance_exam",
    title: "新东方在线考研教研",
    publisher: "新东方在线",
    official_url: "https://kaoyan.koolearn.com/",
    use_for: "复习规划和科目框架；仅作T3教研参考，不作为政策依据",
    freshness: "rolling",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "python-official-docs",
    goal_type: "personal_growth",
    title: "Python 官方语言与标准库文档",
    publisher: "Python Software Foundation",
    official_url: "https://docs.python.org/3/",
    use_for: "Python 语言语法、标准库、异常、模块、异步和运行时边界",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "mdn-web-platform",
    goal_type: "personal_growth",
    title: "MDN Web 开发与 Web API 文档",
    publisher: "MDN Web Docs",
    official_url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
    use_for: "HTML、CSS、JavaScript、HTTP、Fetch 和 Web 可访问性基础",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "git-official-docs",
    goal_type: "personal_growth",
    title: "Git 官方文档",
    publisher: "Git Project",
    official_url: "https://git-scm.com/docs",
    use_for: "版本控制、分支、合并、历史整理和撤销操作",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "postgresql-official-docs",
    goal_type: "personal_growth",
    title: "PostgreSQL 官方文档",
    publisher: "PostgreSQL Global Development Group",
    official_url: "https://www.postgresql.org/docs/current/",
    use_for: "SQL、事务、约束、索引、查询计划和数据库建模基础",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "typescript-official-docs",
    goal_type: "personal_growth",
    title: "TypeScript 官方 Handbook",
    publisher: "Microsoft TypeScript",
    official_url: "https://www.typescriptlang.org/docs/handbook/",
    use_for: "TypeScript 类型、函数、类型收窄和泛型基础",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "owasp-security-guidance",
    goal_type: "personal_growth",
    title: "OWASP Web 与 LLM 安全指导",
    publisher: "OWASP Foundation",
    official_url: "https://owasp.org/Top10/2025/",
    use_for: "Web 风险、认证、输入验证和 LLM 提示词注入的安全边界",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "go-official-docs",
    goal_type: "personal_growth",
    title: "Go 官方语言、工程与模块文档",
    publisher: "The Go Authors",
    official_url: "https://go.dev/doc/",
    use_for: "Go 语言规范、错误处理、并发、模块和工程实践",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "java-official-tutorials",
    goal_type: "personal_growth",
    title: "Oracle Java 官方教程",
    publisher: "Oracle",
    official_url: "https://docs.oracle.com/javase/tutorial/",
    use_for: "Java 对象模型、集合、异常和并发基础；版本特性需回到当前 Java SE 文档",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "linux-kernel-docs",
    goal_type: "personal_growth",
    title: "Linux 内核官方文档",
    publisher: "The Linux Kernel Documentation",
    official_url: "https://docs.kernel.org/",
    use_for: "Linux 进程、内存、网络和内核接口边界；发行版行为需单独核验",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "gcc-official-docs",
    goal_type: "personal_growth",
    title: "GNU Compiler Collection 官方文档",
    publisher: "GNU Project",
    official_url: "https://gcc.gnu.org/onlinedocs/",
    use_for: "C/C++ 编译流程、警告、调试与运行时插桩的工具链边界",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "nist-ai-risk-guidance",
    goal_type: "personal_growth",
    title: "NIST AI 风险管理与评测资源",
    publisher: "National Institute of Standards and Technology",
    official_url: "https://www.nist.gov/itl/ai-risk-management-framework",
    use_for: "AI 风险治理、可信度、测试评估验证确认和持续监测",
    freshness: "rolling",
    region_scope: "全球/通用",
  }),
  Object.freeze({
    id: "github-postgraduate-learning-research",
    goal_type: "postgraduate_entrance_exam",
    title: "GitHub 考研学习资源调研（2026-09-20 快照）",
    publisher: "GitHub 开源仓库与砺境调研",
    official_url: "https://github.com/",
    use_for: "考研数学、408、英语和政治的学习结构、练习形态与证据化行动参考；不替代当年官方大纲和招生政策",
    freshness: "snapshot",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "github-learning-method-research",
    goal_type: "personal_growth",
    title: "GitHub 学习科学与知识管理调研（2026-09-20 快照）",
    publisher: "GitHub 开源仓库与砺境调研",
    official_url: "https://github.com/",
    use_for: "数学资源组织、计算机自学路线、间隔重复和知识管理的学习方法参考；不替代具体课程与官方文档",
    freshness: "snapshot",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "github-ai-education-research",
    goal_type: "personal_growth",
    title: "GitHub AI 教育项目调研（2026-09-20 快照）",
    publisher: "GitHub 开源仓库与砺境调研",
    official_url: "https://github.com/",
    use_for: "AI 辅导、互动课堂、长期学习者记忆和 RAG 产品结构参考；不替代真实学习效果、Provider 可用性或生产评测",
    freshness: "snapshot",
    region_scope: "全国",
  }),
  Object.freeze({
    id: "cet-official-paper-structure",
    goal_type: "college_english_exam",
    title: "全国大学英语四、六级考试笔试考核内容",
    publisher: "教育部教育考试院",
    official_url: "https://cet.neea.edu.cn/html1/folder/16113/1586-1.htm",
    use_for: "核对CET-4/CET-6笔试题型、板块比例和当前考试时长；当次考试安排仍以官方通知及学校考点公告为准",
    freshness: "checked_2026-09-27",
    region_scope: "全国",
  }),
]);

// These are reviewed retrieval anchors, not claims about a current year's dates or eligibility.
// Dynamic facts remain facts_to_confirm and must be checked at the official source.
const BASE_OFFICIAL_KNOWLEDGE_CHUNKS = Object.freeze([
  Object.freeze({
    id: "pg-policy-verification",
    source_id: "moe-postgraduate-admissions",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研政策与管理信息的核验范围",
    content: "涉及考研报名条件、招生管理、考试组织、年度政策或通知时，计划只能把教育部及当年官方公告作为核验依据。模型不得把往年时间、资格条件或经验判断写成今年已经确定的事实。",
    keywords: ["考研", "研究生", "报名", "资格", "政策", "公告", "年度", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "pg-directory-verification",
    source_id: "chsi-postgraduate-directory",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研院校、专业目录与报名信息",
    content: "涉及目标院校、招生单位、专业目录、报名信息或报考地区时，应把中国研究生招生信息网的当年页面作为检索和核验入口。目标院校的具体要求还需要继续核对该校研究生院或招生单位公告。",
    keywords: ["考研", "院校", "专业目录", "招生单位", "报名", "地区", "专业课", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "pg-plan-evidence",
    source_id: "chsi-postgraduate-directory",
    goal_types: ["postgraduate_entrance_exam"],
    region_scope: "全国",
    title: "考研计划的可追溯学习产出",
    content: "考研学习计划应将目标拆成可检查的阶段产出，例如完成范围清单、留下基础诊断、完成错题回顾和形成专业课复述。计划中的动态考试事实必须单独列为待核验事项，不应由模型替用户确认。",
    keywords: ["考研", "计划", "学习产出", "基础诊断", "错题", "专业课", "待核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-national-verification",
    source_id: "national-civil-service-bureau",
    goal_types: ["civil_service_exam"],
    region_scope: "全国",
    title: "国考公告与职位信息的核验范围",
    content: "涉及中央机关及其直属机构的考试公告、职位条件、报名安排或职位信息时，应以国家公务员局发布的当年公告和职位信息为依据。模型不得使用未核验的往年时间、岗位数量或资格条件。",
    keywords: ["考公", "国考", "公务员", "公告", "职位", "报名", "资格", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-regional-verification",
    source_id: "regional-civil-service-notices",
    goal_types: ["civil_service_exam"],
    region_scope: "按报考地区",
    title: "省考地区与资格条件的核验范围",
    content: "涉及省考、地区限制、职位表、资格条件或地方报名安排时，必须按用户报考地区检索对应省级公务员主管部门公告。全国性经验不能替代地方公告，地区不匹配时要标记为待核验。",
    keywords: ["考公", "省考", "地区", "职位表", "资格条件", "报名", "公告", "地方"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cse-plan-evidence",
    source_id: "national-civil-service-bureau",
    goal_types: ["civil_service_exam"],
    region_scope: "全国",
    title: "考公计划的可追溯学习产出",
    content: "考公学习计划应把行测、申论或用户明确的重点拆成可检查的练习、复盘和表达产出。具体考试科目、题型比例和当年要求必须回到对应公告或官方材料核验，不由模型凭记忆补全。",
    keywords: ["考公", "行测", "申论", "练习", "复盘", "表达", "计划", "待核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "shared-source-grounding",
    source_id: "national-smart-education-platform",
    goal_types: ["personal_growth", "employment", "professional_certificate"],
    region_scope: "全国",
    title: "学习资源与目标的来源边界",
    content: "平台可以根据用户目标、基础和可用时间组织学习计划，但课程、证书规则、就业行情或机构要求等外部事实必须标明来源和更新时间。没有可靠来源时，输出应该是学习行动建议，而不是确定性事实。",
    keywords: ["学习", "课程", "证书", "就业", "资源", "来源", "更新时间", "核验"],
    review_status: "reviewed",
  }),
  Object.freeze({
    id: "cet-paper-structure",
    source_id: "cet-official-paper-structure",
    goal_types: ["college_english_exam"],
    region_scope: "全国",
    title: "CET-4 / CET-6 笔试结构与训练边界",
    content: "教育部教育考试院公开的CET笔试由写作、听力理解、阅读理解和翻译构成。当前官方页面列明四级笔试125分钟、六级130分钟；写作和翻译各占15%，听力与阅读各占35%。训练应按板块收集作答和错因，不把站内原创练习当作官方真题，也不从单次练习推断考试成绩。考试日期、考点安排和当次要求须核验最新官方通知及学校考点公告。",
    keywords: ["四六级", "CET", "CET-4", "CET-6", "听力", "阅读", "写作", "翻译", "考试时长", "题型"],
    review_status: "reviewed",
  }),
]);

function importedKnowledgeChunk(entry) {
  const metadata = {
    level1: entry.level1,
    level2: entry.level2,
    audience: entry.audience,
    stage: entry.stage,
    region: entry.region,
    prerequisites: entry.prerequisites,
    related: entry.related,
    source_name: entry.source_name,
    source_type: entry.source_type,
    published_at: entry.published_at,
    validity: entry.validity,
    confidence: entry.confidence,
    update_required: entry.update_required,
    review_schedule: entry.review_schedule,
    claim_status: entry.claim_status,
      review_note: entry.review_note,
      source_tier: entry.source_tier,
      as_of: entry.as_of,
      status: entry.status,
  };
  return Object.freeze({
    id: entry.id,
    source_id: entry.primary_source_id,
    goal_types: [entry.goal_type ?? "postgraduate_entrance_exam"],
    region_scope: entry.region,
    title: entry.title,
    content: [
      `知识结论：${entry.conclusion}`,
      `详细说明：${entry.detail}`,
      `前置条件：${entry.prerequisites}`,
      `可执行步骤：${entry.actions.join("；")}`,
      `常见误区：${entry.pitfalls}`,
      `审核边界：${entry.review_note}`,
    ].join("\n"),
    keywords: [...entry.tags, entry.level1, entry.level2, entry.related].filter(Boolean),
    source_links: [...entry.source_links],
    metadata,
    review_status: entry.review_status,
  });
}

const IMPORTED_KNOWLEDGE_CHUNKS = [
  ...OFFICIAL_KNOWLEDGE_ENTRIES,
  ...TECHNICAL_LEARNING_KNOWLEDGE_ENTRIES,
  ...POSTGRADUATE_PACK_KNOWLEDGE_ENTRIES,
  ...OFFICIAL_TECHNICAL_KNOWLEDGE_ENTRIES,
  ...OFFICIAL_KNOWLEDGE_EXPANSION_V2_ENTRIES,
  ...GITHUB_LEARNING_RESEARCH_ENTRIES,
].map(importedKnowledgeChunk);
const OFFICIAL_KNOWLEDGE_CHUNKS = Object.freeze([
  ...BASE_OFFICIAL_KNOWLEDGE_CHUNKS,
  ...IMPORTED_KNOWLEDGE_CHUNKS,
]);

module.exports = {
  OFFICIAL_KNOWLEDGE_CHUNKS,
  OFFICIAL_SOURCE_REGISTRY,
};
